[package]
name = "cells_redux"
version = "0.1.0"
edition = "2024"

[dependencies]
rune = {git = "https://github.com/rune-rs/rune.git"}
rand = "0.9.1"
clap = { version = "4.5.39", features = ["derive"] }
libnoise = "1.2.0"
random = "0.14.0"
probability = "0.20.3"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"

[[bin]]
name = "rune_test"
path = "src/rune_test.rs"